### PR TITLE
add poem for ben 

### PR DESCRIPTION
**Pull request by b3nnyc**

### CODE REVIEW

**Comment by NickCascella** [comment]
There appears to be a merge conflict. Please resolve the issues then commit again.

**Comment by b3nnyc** [comment]
Overrode colour in CSS file. Added my poem to list of poems.

**Comment by NickCascella** [comment]
Ben i thought i told you to check your stuff before pushing. Try again then commit.

**Comment by b3nnyc** [comment]
Fixed the photo - I promise I will do better next time plz dont fire

**Pull request merged**
