### PR TITLE
added picture to asset

### PR DESCRIPTION
**Pull request by kdelsouz**

### CODE REVIEW

**Comment by NickCascella** [comment]
You haven't done 2/3 requirements! 
- Need to create your poem object
- Need to change background colour 


Please refer to lab instructions next time. Thanks.

**Comment by lor104** [comment]
Kourosh, another branch was merged in the meantime and now there are conflicts. Can you resolve? Thanks

**Comment by kdelsouz** [comment]
Fixed conflict issues with poems and background color.

**Comment by lor104** [comment]
Looks good! Thanks Kourosh!

**Pull request merged**
